name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 14:40 运行一次, 中国时间 22:40
    #- cron: '40 14 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ 45db3d34b9504ce685df242bf218d0ea }}
          GP_TOKEN: ${{ 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 }}
          PUSH_TYPES: 'pushplus'
          DO_NOT_REWARD: 'false'
          PUSHPLUS_TOKEN: ${{ 3ef59957eacb4398ade9fe971f0e8870 }}
